/**
 * Corso Indaco API
 * Api for Corso Indaco
 *
 * The version of the OpenAPI document: V1
 * Contact: riolo.giuseppe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MessageModel { 
    id?: string | null;
    name?: string | null;
    email: string;
    subject?: string | null;
    body: string;
}

